
https://blog.csdn.net/io569417668/article/details/106295308




## ply文件读取三角网格数据并且打印它的顶点和三角形。
open3d有一种被称为TriangleMesh的3d三角网格的数据结构。下面的代码展示了如何从一个ply文件读取三角网格数据并且打印它的顶点和三角形。


TriangleMesh类是有像vertices（顶点）和triangles（三角形）这些数据字段的。open3d通过numpy直接对这些字段进行访问。



In [1]:
import open3d as o3d
import open3d_tutorial as o3dtut
import numpy as np

print("Testing mesh in open3d ...")
mesh = o3dtut.get_knot_mesh()  # 加载03点云/knot.ply文件
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices)) # vertices（顶点）和triangles（三角形）
print('Triangles:')
print(np.asarray(mesh.triangles)) # vertices（顶点）和triangles（三角形）

Testing mesh in open3d ...
TriangleMesh with 1440 points and 2880 triangles.
Vertices:
[[  4.51268387  28.68865967 -76.55680847]
 [  7.63622284  35.52046967 -69.78063965]
 [  6.21986008  44.22465134 -64.82303619]
 ...
 [-22.12651634  31.28466606 -87.37570953]
 [-13.91188431  25.4865818  -86.25827026]
 [ -5.27768707  23.36245346 -81.43279266]]
Triangles:
[[   0   12   13]
 [   0   13    1]
 [   1   13   14]
 ...
 [1438   11 1439]
 [1439   11    0]
 [1439    0 1428]]
